server:
  port: 10741
spring:
  application:
    name: StargazerProjectDistributedSystemVessel
  cloud:
     instance-count: 1
     instance-index: 0
     stream:
        kafka:
          binder:
            brokers: 127.0.0.1:9092
            zk-nodes: 127.0.0.1:2181
            auto-add-partitions: true
            auto-create-topics: true
            min-partition-count: 1
        bindings:
          output:
            destination: OrderPushMessageQueue
            content-type: text/plain
            producer:
              partitionCount: 1
          input:
            destination: OrderAcquireMessageQueue
            group: s1
            consumer:
              concurrency: 1
              partitioned: false
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/